server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://192.168.227.130:3306/gmall_product?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root



mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml


logging:
  level:
    com.atguigu.gmall.product.mapper: debug

